#!/usr/bin/python
import binascii
import string
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_ac_energy_amf_Panel_dg_power_status
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_ac_energy_seb_status(item, _no_params, info):
    """
                check_ac_energy_amf_Panel_dg_power_status function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    new_seb_energy = None
    try:
        if info:
            if info[0][0]:
                seb_energy = info[0][0]
		try:
		    new_seb_energy = float(seb_energy)
		except Exception,e: 
		    new_seb_energy = seb_energy.replace(' ','@')
                state = 0
                infotext = "seb_energy=%s" % new_seb_energy
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("seb_energy",new_seb_energy)])

# This check works on all SNMP hosts

check_info["ac_energy_seb_status"] = {
    'check_function':          check_ac_energy_seb_status,
    'service_description':     'ac_energy_seb_status',
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.19', ['9.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}


