#!/usr/bin/python
import binascii
import string
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_dg_power_total
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

#def inventory_dg_power_total_status(info):
#    if info[0][0]:
#        return [ (None, None) ]


def check_dc_battdischarge_counter_status(item, params, info):
    """
                check_dg_power_total_status function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    discharge_counter =None
    try:
        if info:
            if info[0][0]:
                discharge_counter = info[0][0]
                try:
	            discharge_counter=float(discharge_counter)
		except Exception, e :
		    discharge_counter = info[0][0].replace(' ','@')
		state = 0
                infotext = "battdischarge_counter=%s" % discharge_counter
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("battdischarge_counter",discharge_counter)])

# This check works on all SNMP hosts

check_info["dc_battdischarge_counter_status"] = {
    'check_function':          check_dc_battdischarge_counter_status,
    'service_description':     'dc_battdischarge_counter_status',
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.2.10', ['4.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}


