#!/usr/bin/python
import binascii
import string
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_dg_power_total
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def inventory_dg_power_total_status(info):
    if info[0][0]:
        return [ (None, None) ]


def check_dg_power_total_status(item, _no_params, info):
    """
                check_dg_power_total_status function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    new_total_power=None
    try:
        if info:
            if info[0][0]:
                total_power = info[0][0]
		try:
		    new_total_power = float(total_power)
		except Exception,e:
		    new_total_power = info[0][0].replace(' ','@')
                state = 0
                infotext = "total_power=%s" % new_total_power
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("total_power",new_total_power)])

# This check works on all SNMP hosts

check_info["dg_power_total_status"] = {
    'check_function':          check_dg_power_total_status,
    'inventory_function':      inventory_dg_power_total_status,
    'service_description':     'dg_power_total_status',
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.19', ['5.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}


