#!/usr/bin/python
"""
solarrHVLVInstallationDate of poller device.

This is part of device application.
Poller script determines the solarrHVLVInstallationDate of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.9.8.2.1.2 from snmp agent of device at specific interval.
Device solarrHVLVInstallationDate is sent to device application

"""
# ######################################################################
# Function: check_ec500_inventory_solar_hvlv_installdt_invent
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device inventory_solar_hvlv_installdt
# ######################################################################
ec500_inventory_solar_hvlv_installdt_default_levels = ()

def check_ec500_inventory_solar_hvlv_installdt_invent(item, params, info):
    """
            check_ec500_inventory_solar_hvlv_installdt_invent function fetches the solarrHVLVInstallationDate

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    try:
        state = 0
        for line in info:
            index= index + 1
            ec500_inventory_solar_hvlv_installdt  = line[0]
            try :
                ec500_inventory_solar_hvlv_installdt = float(info[0][0])
            except Exception,e:
                ec500_inventory_solar_hvlv_installdt = str(info[0][0].replace(" ","@"))
            perf_data.append(("ec500_inventory_solar_hvlv_installdt_%d" %index,ec500_inventory_solar_hvlv_installdt))
            infotext = "ec500_inventory_solar_hvlv_installdt" % ec500_inventory_solar_hvlv_installdt
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perf_data)




# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_inventory_solar_hvlv_installdt_invent"] = {
    'check_function':          check_ec500_inventory_solar_hvlv_installdt_invent,
    'service_description':     'ec500_inventory_solar_hvlv_installdt_invent',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device solarrHVLVInstallationDate
#########################################################################
snmp_info["ec500_inventory_solar_hvlv_installdt_invent"] = ('.1.3.6.1.4.1.38016.14.9.8.2', ['1.2.0'])
