#!/usr/bin/python
"""
recTempratureRise of poller device.

This is part of device application.
Poller script determines the recTempratureRise of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.8.6.1.18 from snmp agent of device at specific interval.
Device recTempratureRise is sent to device application

"""
# ######################################################################
# Function: check_ec500_rectifierindiv_rect_temp_rise
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device rectifierindiv_rect_temp_rise
# ######################################################################
ec500_rectifierindiv_rect_temp_rise_default_levels = ()

def check_ec500_rectifierindiv_rect_temp_rise(item, params, info):
    """
            check_ec500_rectifierindiv_rect_temp_rise function fetches the recTempratureRise

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    index = 0
    perfdata = []
    ec500_rectifierindiv_rect_temp_rise = None
    try:
        #print info
        for line in info:
            index= index + 1
            ec500_rectifierindiv_rect_temp_rise = line[0]
            #print rec_share_value 
            try:
                ec500_rectifierindiv_rect_temp_rise = float(ec500_rectifierindiv_rect_temp_rise)
            except Exception,e:
                ec500_rectifierindiv_rect_temp_rise = line[0].replace(' ','@')
            state = 0
            perfdata.append(("ec500_rectifierindiv_rect_%d_temp_rise" %index,ec500_rectifierindiv_rect_temp_rise))
            infotext = "ec500_rectifierindiv_rect_temp_rise=%s" % ec500_rectifierindiv_rect_temp_rise
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_rectifierindiv_rect_temp_rise"] = {
    'check_function':          check_ec500_rectifierindiv_rect_temp_rise,
    'service_description':     'ec500_rectifierindiv_rect_temp_rise',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device recTempratureRise
#########################################################################
snmp_info["ec500_rectifierindiv_rect_temp_rise"] = ('.1.3.6.1.4.1.38016.14.2.8.6', ['1.18'])
