#!/usr/bin/python
"""
liionBattBankChargeVoltage of poller device.

This is part of device application.
Poller script determines the liionBattBankChargeVoltage of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.11 from snmp agent of device at specific interval.
Device liionBattBankChargeVoltage is sent to device application

"""
# ######################################################################
# Function: check_ec500_lion_battery_charge_volt_invent
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lion_battery_charge_volt
# ######################################################################
ec500_lion_battery_charge_volt_default_levels = ()

def check_ec500_lion_battery_charge_volt_invent(item, params, info):
    """
            check_ec500_lion_battery_charge_volt_invent function fetches the liionBattBankChargeVoltage

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                ec500_lion_battery_charge_volt = float(info[0][0])
            except Exception,e:
                ec500_lion_battery_charge_volt = str(info[0][0].replace(" ","@"))
            perf_data = [("ec500_lion_battery_charge_volt", ec500_lion_battery_charge_volt)]
            return (state, "ec500_lion_battery_charge_volt=%s" % ec500_lion_battery_charge_volt, perf_data)
        except Exception,e:
            return (3, "ec500_lion_battery_charge_volt=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "ec500_lion_battery_charge_volt=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_lion_battery_charge_volt_invent"] = {
    'check_function':          check_ec500_lion_battery_charge_volt_invent,
    'service_description':     'ec500_lion_battery_charge_volt_invent',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device liionBattBankChargeVoltage
#########################################################################
snmp_info["ec500_lion_battery_charge_volt_invent"] = ('.1.3.6.1.4.1.38016.14', ['11.11'])
