#!/usr/bin/python
"""
moduleStateOfHealth of poller device.

This is part of device application.
Poller script determines the moduleStateOfHealth of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.28.1.7 from snmp agent of device at specific interval.
Device moduleStateOfHealth is sent to device application

"""
# ######################################################################
# Function: check_ec500_lionindiv_module_soh
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lionindiv_module_soh
# ######################################################################
ec500_lionindiv_module_soh_default_levels = ()

def check_ec500_lionindiv_module_soh(item, params, info):
    """
            check_ec500_lionindiv_module_soh function fetches the moduleStateOfHealth

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    try:
        state = 0
        for line in info:
            index= index + 1
            ec500_lionindiv_module_soh  = line[0]
            try :
                ec500_lionindiv_module_soh = float(info[0][0])
            except Exception,e:
                ec500_lionindiv_module_soh = str(info[0][0].replace(" ","@"))
            perf_data.append(("ec500_lionindiv_module_soh_%d" %index,ec500_lionindiv_module_soh))
            infotext = "ec500_lionindiv_module_soh" % ec500_lionindiv_module_soh
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perf_data)




# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_lionindiv_module_soh"] = {
    'check_function':          check_ec500_lionindiv_module_soh,
    'service_description':     'ec500_lionindiv_module_soh',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device moduleStateOfHealth
#########################################################################
snmp_info["ec500_lionindiv_module_soh"] = ('.1.3.6.1.4.1.38016.14.11.28', ['1.7'])
