#!/usr/bin/python
"""
solarRecRunTime of poller device.

This is part of device application.
Poller script determines the solarRecRunTime of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.10.6.1.8 from snmp agent of device at specific interval.
Device solarRecRunTime is sent to device application

"""
# ######################################################################
# Function: check_ec500_solarindiv_rec_run_time_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device solarindiv_rec_run_time
# ######################################################################
ec500_solarindiv_rec_run_time_default_levels = ()

def check_ec500_solarindiv_rec_run_time_status(item, params, info):
    """
            check_ec500_solarindiv_rec_run_time_status function fetches the solarRecRunTime

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    try:
        state = 0
        for line in info:
            index= index + 1
            ec500_solarindiv_rec_run_time  = line[0]
            try :
                ec500_solarindiv_rec_run_time = float(info[0][0])
            except Exception,e:
                ec500_solarindiv_rec_run_time = str(info[0][0].replace(" ","@"))
            perf_data.append(("ec500_solarindiv_rec_%d_run_time" %index,ec500_solarindiv_rec_run_time))
            infotext = "ec500_solarindiv_rec_run_time" % ec500_solarindiv_rec_run_time
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perf_data)




# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_solarindiv_rec_run_time_status"] = {
    'check_function':          check_ec500_solarindiv_rec_run_time_status,
    'service_description':     'ec500_solarindiv_rec_run_time_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device solarRecRunTime
#########################################################################
snmp_info["ec500_solarindiv_rec_run_time_status"] = ('.1.3.6.1.4.1.38016.14.10.6', ['1.8'])
