#!/usr/bin/python
"""
liionBattBankRemainingAH of poller device.

This is part of device application.
Poller script determines the liionBattBankRemainingAH of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.5 from snmp agent of device at specific interval.
Device liionBattBankRemainingAH is sent to device application

"""
# ######################################################################
# Function: check_ec500_lion_battery_remaining_ah
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lion_battery_remaining_ah
# ######################################################################
ec500_lion_battery_remaining_ah_default_levels = ()

def check_ec500_lion_battery_remaining_ah(item, params, info):
    """
            check_ec500_lion_battery_remaining_ah function fetches the liionBattBankRemainingAH

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                ec500_lion_battery_remaining_ah = float(info[0][0])
            except Exception,e:
                ec500_lion_battery_remaining_ah = str(info[0][0].replace(" ","@"))
            perf_data = [("ec500_lion_battery_remaining_ah", ec500_lion_battery_remaining_ah)]
            return (state, "ec500_lion_battery_remaining_ah=%s" % ec500_lion_battery_remaining_ah, perf_data)
        except Exception,e:
            return (3, "ec500_lion_battery_remaining_ah=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "ec500_lion_battery_remaining_ah=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_lion_battery_remaining_ah"] = {
    'check_function':          check_ec500_lion_battery_remaining_ah,
    'service_description':     'ec500_lion_battery_remaining_ah',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device liionBattBankRemainingAH
#########################################################################
snmp_info["ec500_lion_battery_remaining_ah"] = ('.1.3.6.1.4.1.38016.14', ['11.5'])
