#!/usr/bin/python
"""
recLine1InputVoltage of poller device.

This is part of device application.
Poller script determines the recLine1InputVoltage of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.8.6.1.7 from snmp agent of device at specific interval.
Device recLine1InputVoltage is sent to device application

"""
# ######################################################################
# Function: check_ec500_rectifierindiv_recline1_input_voltage
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device rectifierindiv_recline1_input_voltage
# ######################################################################
ec500_rectifierindiv_recline1_input_voltage_default_levels = ()

def check_ec500_rectifierindiv_recline1_input_voltage(item, params, info):
    """
            check_ec500_rectifierindiv_recline1_input_voltage function fetches the recLine1InputVoltage

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    index = 0
    perfdata = []
    ec500_rectifierindiv_recline1_input_voltage = None
    try:
        #print info
        for line in info:
            index= index + 1
            ec500_rectifierindiv_recline1_input_voltage = line[0]
            #print rec_share_value 
            try:
                ec500_rectifierindiv_recline1_input_voltage = float(ec500_rectifierindiv_recline1_input_voltage)
            except Exception,e:
                ec500_rectifierindiv_recline1_input_voltage = line[0].replace(' ','@')
            state = 0
            perfdata.append(("ec500_rectifierindiv_recline1_input_%d_voltage" %index,ec500_rectifierindiv_recline1_input_voltage))
            infotext = "ec500_rectifierindiv_recline1_input_voltage=%s" % ec500_rectifierindiv_recline1_input_voltage
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_rectifierindiv_recline1_input_voltage"] = {
    'check_function':          check_ec500_rectifierindiv_recline1_input_voltage,
    'service_description':     'ec500_rectifierindiv_recline1_input_voltage',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device recLine1InputVoltage
#########################################################################
snmp_info["ec500_rectifierindiv_recline1_input_voltage"] = ('.1.3.6.1.4.1.38016.14.2.8.6', ['1.7'])
