#!/usr/bin/python
"""
rectOutputVoltage of poller device.

This is part of device application.
Poller script determines the rectOutputVoltage of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.8.6.1.16 from snmp agent of device at specific interval.
Device rectOutputVoltage is sent to device application

"""
# ######################################################################
# Function: check_ec500_rectifierindiv_rect_output_voltage
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device rectifierindiv_rect_output_voltage
# ######################################################################
ec500_rectifierindiv_rect_output_voltage_default_levels = ()

def check_ec500_rectifierindiv_rect_output_voltage(item, params, info):
    """
            check_ec500_rectifierindiv_rect_output_voltage function fetches the rectOutputVoltage

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    index = 0
    perfdata = []
    ec500_rectifierindiv_rect_output_voltage = None
    try:
        #print info
        for line in info:
            index= index + 1
            ec500_rectifierindiv_rect_output_voltage = line[0]
            #print rec_share_value 
            try:
                ec500_rectifierindiv_rect_output_voltage = float(ec500_rectifierindiv_rect_output_voltage)
            except Exception,e:
                ec500_rectifierindiv_rect_output_voltage = line[0].replace(' ','@')
            state = 0
            perfdata.append(("ec500_rectifierindiv_rect_%d_output_voltage" %index,ec500_rectifierindiv_rect_output_voltage))
            infotext = "ec500_rectifierindiv_rect_output_voltage=%s" % ec500_rectifierindiv_rect_output_voltage
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_rectifierindiv_rect_output_voltage"] = {
    'check_function':          check_ec500_rectifierindiv_rect_output_voltage,
    'service_description':     'ec500_rectifierindiv_rect_output_voltage',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device rectOutputVoltage
#########################################################################
snmp_info["ec500_rectifierindiv_rect_output_voltage"] = ('.1.3.6.1.4.1.38016.14.2.8.6', ['1.16'])
