#!/usr/bin/python
"""
solarCumulativeRunhrs of poller device.

This is part of device application.
Poller script determines the solarCumulativeRunhrs of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.10.5 from snmp agent of device at specific interval.
Device solarCumulativeRunhrs is sent to device application

"""
# ######################################################################
# Function: check_ec500_solar_cum_runhrs_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device solar_cum_runhrs
# ######################################################################
ec500_solar_cum_runhrs_default_levels = ()

def check_ec500_solar_cum_runhrs_status(item, params, info):
    """
            check_ec500_solar_cum_runhrs_status function fetches the solarCumulativeRunhrs

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                ec500_solar_cum_runhrs = float(info[0][0])
            except Exception,e:
                ec500_solar_cum_runhrs = str(info[0][0].replace(" ","@"))
            perf_data = [("ec500_solar_cum_runhrs", ec500_solar_cum_runhrs)]
            return (state, "ec500_solar_cum_runhrs=%s" % ec500_solar_cum_runhrs, perf_data)
        except Exception,e:
            return (3, "ec500_solar_cum_runhrs=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "ec500_solar_cum_runhrs=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_solar_cum_runhrs_status"] = {
    'check_function':          check_ec500_solar_cum_runhrs_status,
    'service_description':     'ec500_solar_cum_runhrs_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device solarCumulativeRunhrs
#########################################################################
snmp_info["ec500_solar_cum_runhrs_status"] = ('.1.3.6.1.4.1.38016.14.10', ['5.0'])
