#!/usr/bin/python
"""
rectifier_maxrect_invent of poller device.

This is part of device application.
Poller script determines the rectifier_maxrect_invent of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.8.1 from snmp agent of device at specific interval.
Device rectifier_maxrect_invent is sent to device application

"""
# ######################################################################
# Function: check_ec500_rectifier_maxrect_invent
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device rectifier_maxrect
# ######################################################################
ec500_rectifier_maxrect_default_levels = ()

def check_ec500_rectifier_maxrect_invent(item, params, info):
    """
            check_ec500_rectifier_maxrect_invent function fetches the rectifier_maxrect_invent

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                ec500_rectifier_maxrect = float(info[0][0])
            except Exception,e:
                ec500_rectifier_maxrect = str(info[0][0].replace(" ","@"))
            perf_data = [("ec500_rectifier_maxrect", ec500_rectifier_maxrect)]
            return (state, "ec500_rectifier_maxrect=%s" % ec500_rectifier_maxrect, perf_data)
        except Exception,e:
            return (3, "ec500_rectifier_maxrect=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "ec500_rectifier_maxrect=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_rectifier_maxrect_invent"] = {
    'check_function':          check_ec500_rectifier_maxrect_invent,
    'service_description':     'ec500_rectifier_maxrect_invent',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device rectifier_maxrect_invent
#########################################################################
snmp_info["ec500_rectifier_maxrect_invent"] = ('.1.3.6.1.4.1.38016.14.2', ['8.1'])
