#!/usr/bin/python
"""
solarHVLVInventoryCount of poller device.

This is part of device application.
Poller script determines the solarHVLVInventoryCount of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.9.8.1 from snmp agent of device at specific interval.
Device solarHVLVInventoryCount is sent to device application

"""
# ######################################################################
# Function: check_ec500_solar_hvlv_inventory_count
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device solar_hvlv_inventory_count
# ######################################################################
ec500_solar_hvlv_inventory_count_default_levels = ()

def check_ec500_solar_hvlv_inventory_count(item, params, info):
    """
            check_ec500_solar_hvlv_inventory_count function fetches the solarHVLVInventoryCount

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                ec500_solar_hvlv_inventory_count = float(info[0][0])
            except Exception,e:
                ec500_solar_hvlv_inventory_count = str(info[0][0].replace(" ","@"))
            perf_data = [("ec500_solar_hvlv_inventory_count", ec500_solar_hvlv_inventory_count)]
            return (state, "ec500_solar_hvlv_inventory_count=%s" % ec500_solar_hvlv_inventory_count, perf_data)
        except Exception,e:
            return (3, "ec500_solar_hvlv_inventory_count=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "ec500_solar_hvlv_inventory_count=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["ec500_solar_hvlv_inventory_count"] = {
    'check_function':          check_ec500_solar_hvlv_inventory_count,
    'service_description':     'ec500_solar_hvlv_inventory_count',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device solarHVLVInventoryCount
#########################################################################
snmp_info["ec500_solar_hvlv_inventory_count"] = ('.1.3.6.1.4.1.38016.14.9.8', ['1.0'])
