#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_ac_energy_phase1_voltage
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

lvd_status_dict = {
12 : 'isolated',
13 : 'batteryLVD'
}
def check_general_lvd_batterystatus(item, _no_params, info):
    """
                ac_energy_phase1_voltage function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    lvd_batterystate =None
    try:
        if info:
            if info[0][0]:
		try:
                    lvd_status = int(info[0][0])
		    lvd_bt_state = lvd_status_dict.get(lvd_status)
		    if lvd_bt_state:
			lvd_batterystate = 1
		    else:
			lvd_batterystate =0
                except Exception,e:
                    lvd_batterystate =None
                state = 0
                infotext = "lvd_battery_status=%s" % lvd_batterystate
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("lvd_battery_status",lvd_batterystate)])

# This check works on all SNMP hosts

check_info["general_lvd_batterystatus"] = {
    'check_function':          check_general_lvd_batterystatus,
    'service_description':     'general_lvd_batterystatus',
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.2.11', ['31.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}


