#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_exicom_model_no_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################
#def inventory_inventory_dcif_install_date_invent(info):
#    if info[0][0]:
#        return [ (None, None) ]

def check_inventory_dcif_install_date_invent(item, _no_params, info):
    """
                check_exicom_model_no_invent function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    install_date = None
    index =0
    infotext = "unknown_value"
    perfdata = []
    try:
	if info:
            if info[0][0]:
                install_date = info[0][0].replace(' ','@')
                state = 0
                infotext = "dcif_install_date=%s" % install_date
                perfdata.append(("dcif_install_date", install_date))

    except Exception,e:
        infotext = "dcif_install_date=unknown_value"
    return (state,infotext,perfdata)

check_info["inventory_dcif_install_date_invent"] = {
    'check_function':          check_inventory_dcif_install_date_invent,
    #'inventory_function':     inventory_inventory_dcif_install_date_invent,
    'service_description':     'inventory_dcif_install_date_invent',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.9.6.2', ['1.2']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

