#!/usr/bin/python
"""
moduleCurrent of poller device.

This is part of device application.
Poller script determines the moduleCurrent of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.28.1.4 from snmp agent of device at specific interval.
Device moduleCurrent is sent to device application

"""
# ######################################################################
# Function: check_m2000_lionindiv_module_temp
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lionindiv_module_temp
# ######################################################################
m2000_lionindiv_module_temp_default_levels = ()

def check_m2000_lionindiv_module_temp(item, params, info):
    """
            check_m2000_lionindiv_module_temp function fetches the moduleCurrent

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    try:
        state = 0
        for line in info:
            index= index + 1
            m2000_lionindiv_module_temp  = line[0]
            try :
                m2000_lionindiv_module_temp = float(info[0][0])
            except Exception,e:
                m2000_lionindiv_module_temp = str(info[0][0].replace(" ","@"))
            perf_data.append(("m2000_lionindiv_module_temp_%d" %index,m2000_lionindiv_module_temp))
            infotext = "m2000_lionindiv_module_temp" % m2000_lionindiv_module_temp
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perf_data)




# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_lionindiv_module_temp"] = {
    'check_function':          check_m2000_lionindiv_module_temp,
    'service_description':     'm2000_lionindiv_module_temp',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device moduleCurrent
#########################################################################
snmp_info["m2000_lionindiv_module_temp"] = ('.1.3.6.1.4.1.38016.14.11.28', ['1.4'])
