#!/usr/bin/python
"""
rectifierSerialNumber of poller device.

This is part of device application.
Poller script determines the rectifierSerialNumber of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.8.6.1.2 from snmp agent of device at specific interval.
Device rectifierSerialNumber is sent to device application

"""
# ######################################################################
# Function: check_m2000_rectifierindiv_serial_no_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device rectifierindiv_serial_no
# ######################################################################
m2000_rectifierindiv_serial_no_default_levels = ()

def check_m2000_rectifierindiv_serial_no_status(item, params, info):
    """
            check_m2000_rectifierindiv_serial_no_status function fetches the rectifierSerialNumber

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    index = 0
    perfdata = []
    m2000_rectifierindiv_serial_no = None
    try:
        #print info
        for line in info:
            index= index + 1
            m2000_rectifierindiv_serial_no = line[0]
            #print rec_share_value 
            try:
                m2000_rectifierindiv_serial_no = float(m2000_rectifierindiv_serial_no)
            except Exception,e:
                m2000_rectifierindiv_serial_no = line[0].replace(' ','@')
            state = 0
            perfdata.append(("m2000_rectifierindiv_%d_serial_no" %index,m2000_rectifierindiv_serial_no))
            infotext = "m2000_rectifierindiv_serial_no=%s" % m2000_rectifierindiv_serial_no
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_rectifierindiv_serial_no_status"] = {
    'check_function':          check_m2000_rectifierindiv_serial_no_status,
    'service_description':     'm2000_rectifierindiv_serial_no_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device rectifierSerialNumber
#########################################################################
snmp_info["m2000_rectifierindiv_serial_no_status"] = ('.1.3.6.1.4.1.38016.14.2.8.6', ['1.2'])
