#!/usr/bin/python
"""
intalledLiionModule of poller device.

This is part of device application.
Poller script determines the intalledLiionModule of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.1 from snmp agent of device at specific interval.
Device intalledLiionModule is sent to device application

"""
# ######################################################################
# Function: check_m2000_lion_battery_installed_module_invent
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lion_battery_installed_module
# ######################################################################
m2000_lion_battery_installed_module_default_levels = ()

def check_m2000_lion_battery_installed_module_invent(item, params, info):
    """
            check_m2000_lion_battery_installed_module_invent function fetches the intalledLiionModule

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                m2000_lion_battery_installed_module = float(info[0][0])
            except Exception,e:
                m2000_lion_battery_installed_module = str(info[0][0].replace(" ","@"))
            perf_data = [("m2000_lion_battery_installed_module", m2000_lion_battery_installed_module)]
            return (state, "m2000_lion_battery_installed_module=%s" % m2000_lion_battery_installed_module, perf_data)
        except Exception,e:
            return (3, "m2000_lion_battery_installed_module=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "m2000_lion_battery_installed_module=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_lion_battery_installed_module_invent"] = {
    'check_function':          check_m2000_lion_battery_installed_module_invent,
    'service_description':     'm2000_lion_battery_installed_module_invent',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device intalledLiionModule
#########################################################################
snmp_info["m2000_lion_battery_installed_module_invent"] = ('.1.3.6.1.4.1.38016.14', ['11.1'])
