#!/usr/bin/python
"""
activeLiionModule of poller device.

This is part of device application.
Poller script determines the activeLiionModule of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.2 from snmp agent of device at specific interval.
Device activeLiionModule is sent to device application

"""
# ######################################################################
# Function: check_m2000_lion_battery_active_module
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lion_battery_active_module
# ######################################################################
m2000_lion_battery_active_module_default_levels = ()

def check_m2000_lion_battery_active_module(item, params, info):
    """
            check_m2000_lion_battery_active_module function fetches the activeLiionModule

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                m2000_lion_battery_active_module = float(info[0][0])
            except Exception,e:
                m2000_lion_battery_active_module = str(info[0][0].replace(" ","@"))
            perf_data = [("m2000_lion_battery_active_module", m2000_lion_battery_active_module)]
            return (state, "m2000_lion_battery_active_module=%s" % m2000_lion_battery_active_module, perf_data)
        except Exception,e:
            return (3, "m2000_lion_battery_active_module=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "m2000_lion_battery_active_module=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_lion_battery_active_module"] = {
    'check_function':          check_m2000_lion_battery_active_module,
    'service_description':     'm2000_lion_battery_active_module',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device activeLiionModule
#########################################################################
snmp_info["m2000_lion_battery_active_module"] = ('.1.3.6.1.4.1.38016.14', ['11.2'])
