#!/usr/bin/python
"""
load1Voltage of poller device.

This is part of device application.
Poller script determines the load1Voltage of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.12.12 from snmp agent of device at specific interval.
Device load1Voltage is sent to device application

"""
# ######################################################################
# Function: check_m2000_load_voltage
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device load_voltage
# ######################################################################
m2000_load_voltage_default_levels = ()

def check_m2000_load_voltage(item, params, info):
    """
            check_m2000_load_voltage function fetches the load1Voltage

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    index = 0
    perfdata = []
    m2000_load_voltage = None
    try:
        #print info
        for line in info:
            index= index + 1
            m2000_load_voltage = line[0]
            #print rec_share_value 
            try:
                m2000_load_voltage = float(m2000_load_voltage)
            except Exception,e:
                m2000_load_voltage = line[0].replace(' ','@')
            state = 0
            perfdata.append(("m2000_load_voltage",m2000_load_voltage))
            infotext = "m2000_load_voltage=%s" % m2000_load_voltage
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)



# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_load_voltage"] = {
    'check_function':          check_m2000_load_voltage,
    'service_description':     'm2000_load_voltage',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device load1Voltage
#########################################################################
snmp_info["m2000_load_voltage"] = ('.1.3.6.1.4.1.38016.14.2', ['12.12'])
