#!/usr/bin/python
"""
dc_battcharge_counter_status of poller device.

This is part of device application.
Poller script determines the dc_battcharge_counter_status of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.2.10.1 from snmp agent of device at specific interval.
Device dc_battcharge_counter_status is sent to device application

"""
# ######################################################################
# Function: check_m2000_dc_battcharge_counter_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device dc_battcharge_counter
# ######################################################################
m2000_dc_battcharge_counter_default_levels = ()

def check_m2000_dc_battcharge_counter_status(item, params, info):
    """
            check_m2000_dc_battcharge_counter_status function fetches the dc_battcharge_counter_status

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                m2000_dc_battcharge_counter = float(info[0][0])
            except Exception,e:
                m2000_dc_battcharge_counter = str(info[0][0].replace(" ","@"))
            perf_data = [("m2000_dc_battcharge_counter", m2000_dc_battcharge_counter)]
            return (state, "m2000_dc_battcharge_counter=%s" % m2000_dc_battcharge_counter, perf_data)
        except Exception,e:
            return (3, "m2000_dc_battcharge_counter=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "m2000_dc_battcharge_counter=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_dc_battcharge_counter_status"] = {
    'check_function':          check_m2000_dc_battcharge_counter_status,
    'service_description':     'm2000_dc_battcharge_counter_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device dc_battcharge_counter_status
#########################################################################
snmp_info["m2000_dc_battcharge_counter_status"] = ('.1.3.6.1.4.1.38016.14.2', ['10.1'])
