#!/usr/bin/python
"""
amfPanelDgEnergy of poller device.

This is part of device application.
Poller script determines the amfPanelDgEnergy of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.18.8 from snmp agent of device at specific interval.
Device amfPanelDgEnergy is sent to device application

"""
# ######################################################################
# Function: check_m2000_ac_energy_amf_panel_dg_energy_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device ac_energy_amf_panel_dg_energy
# ######################################################################
m2000_ac_energy_amf_panel_dg_energy_default_levels = ()

def check_m2000_ac_energy_amf_panel_dg_energy_status(item, params, info):
    """
            check_m2000_ac_energy_amf_panel_dg_energy_status function fetches the amfPanelDgEnergy

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                m2000_ac_energy_amf_panel_dg_energy = float(info[0][0])
            except Exception,e:
                m2000_ac_energy_amf_panel_dg_energy = str(info[0][0].replace(" ","@"))
            perf_data = [("m2000_ac_energy_amf_panel_dg_energy", m2000_ac_energy_amf_panel_dg_energy)]
            return (state, "m2000_ac_energy_amf_panel_dg_energy=%s" % m2000_ac_energy_amf_panel_dg_energy, perf_data)
        except Exception,e:
            return (3, "m2000_ac_energy_amf_panel_dg_energy=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "m2000_ac_energy_amf_panel_dg_energy=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_ac_energy_amf_panel_dg_energy_status"] = {
    'check_function':          check_m2000_ac_energy_amf_panel_dg_energy_status,
    'service_description':     'm2000_ac_energy_amf_panel_dg_energy_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device amfPanelDgEnergy
#########################################################################
snmp_info["m2000_ac_energy_amf_panel_dg_energy_status"] = ('.1.3.6.1.4.1.38016.14', ['18.8'])
