#!/usr/bin/python
"""
amfPanelMainsPower of poller device.

This is part of device application.
Poller script determines the amfPanelMainsPower of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.18.5 from snmp agent of device at specific interval.
Device amfPanelMainsPower is sent to device application

"""
# ######################################################################
# Function: check_m2000_ac_energy_amf_panel_power_status
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device ac_energy_amf_panel_power
# ######################################################################
m2000_ac_energy_amf_panel_power_default_levels = ()

def check_m2000_ac_energy_amf_panel_power_status(item, params, info):
    """
            check_m2000_ac_energy_amf_panel_power_status function fetches the amfPanelMainsPower

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    if info:
        try:
            state = 0
            try :
                m2000_ac_energy_amf_panel_power = float(info[0][0])
            except Exception,e:
                m2000_ac_energy_amf_panel_power = str(info[0][0].replace(" ","@"))
            perf_data = [("m2000_ac_energy_amf_panel_power", m2000_ac_energy_amf_panel_power)]
            return (state, "m2000_ac_energy_amf_panel_power=%s" % m2000_ac_energy_amf_panel_power, perf_data)
        except Exception,e:
            return (3, "m2000_ac_energy_amf_panel_power=%s" % infotext.replace(" ","@"), perf_data)
    else:
        return (state, "m2000_ac_energy_amf_panel_power=%s" %"No data retrieved".replace(" ","@"), perf_data)


# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_ac_energy_amf_panel_power_status"] = {
    'check_function':          check_m2000_ac_energy_amf_panel_power_status,
    'service_description':     'm2000_ac_energy_amf_panel_power_status',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device amfPanelMainsPower
#########################################################################
snmp_info["m2000_ac_energy_amf_panel_power_status"] = ('.1.3.6.1.4.1.38016.14', ['18.5'])
