#!/usr/bin/python
"""
moduleVoltage of poller device.

This is part of device application.
Poller script determines the moduleVoltage of device.
poller script takes the snmp value of OID .1.3.6.1.4.1.38016.14.11.28.1.3 from snmp agent of device at specific interval.
Device moduleVoltage is sent to device application

"""
# ######################################################################
# Function: check_m2000_lionindiv_module_voltage
#
# Parameters: info (SNMP Ouput) params (No Parameters)
#
# Output: device lionindiv_module_voltage
# ######################################################################
m2000_lionindiv_module_voltage_default_levels = ()

def check_m2000_lionindiv_module_voltage(item, params, info):
    """
            check_m2000_lionindiv_module_voltage function fetches the moduleVoltage

            Args:
                    item (str) Specific item on SNMP output on which we want to filter results

            Kwargs:
                    params (tuple) Check parameters for critical and warning state of service

            Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                                        3: unknown
                        infotext(string):
                                    plugin output
                                    Example : OK - ;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    perf_data = ['']
    try:
        state = 0
        for line in info:
            index= index + 1
            m2000_lionindiv_module_voltage  = line[0]
            try :
                m2000_lionindiv_module_voltage = float(info[0][0])
            except Exception,e:
                m2000_lionindiv_module_voltage = str(info[0][0].replace(" ","@"))
            perf_data.append(("m2000_lionindiv_module_voltage_%d" %index,m2000_lionindiv_module_voltage))
            infotext = "m2000_lionindiv_module_voltage" % m2000_lionindiv_module_voltage
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perf_data)




# This check works on all SNMP hosts
"""
    Dictionary-based declaration of all check types
"""
check_info["m2000_lionindiv_module_voltage"] = {
    'check_function':          check_m2000_lionindiv_module_voltage,
    'service_description':     'm2000_lionindiv_module_voltage',
    'has_perfdata':		True,
}

#########################################################################
#	SNMP OID for the device moduleVoltage
#########################################################################
snmp_info["m2000_lionindiv_module_voltage"] = ('.1.3.6.1.4.1.38016.14.11.28', ['1.3'])
