#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_exicom_model_no_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

#def inventory_rectifier_total_rec_current(info):
#    if info[0][0]:
#        return [ (None, None) ]
def check_rectifierindiv_serial_no_status(item, _no_params, info):
    """
                check_exicom_model_no_invent function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    serial_no = None
    index =0
    perfdata = []
    try:
        for line in info:
            index= index + 1
            serial_no = line[0]
            state = 0
            perfdata.append(("%d_serial_number" %index,serial_no))
            infotext = "serial_number=%s" % serial_no
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)

check_info["rectifierindiv_serial_no_status"] = {
    'check_function':          check_rectifierindiv_serial_no_status,
    'service_description':     'rectifierindiv_serial_no_status',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.2.8.6', ['1.2']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

