#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.60.30.1.30 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_rectifier_serial_number
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_rectifier_serial_number(item, _no_params, info):
    """
                check_rectifier_serial_number 

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    serial_number = None
    index =0
    perfdata = []
    try:
        for line in info:
            index= index + 1
            serial_number = line[0]
            try:
                serial_number = float(serial_number)
            except Exception,e:
                serial_number = line[0].replace(' ','@')
            state = 0
            perfdata.append(("rectifier_%d_serial_number" % index,serial_number))
            infotext = "rectifier_serial_number=%s" % serial_number
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)

check_info["rectifier_serial_number"] = {
    'check_function':          check_rectifier_serial_number,
    'service_description':     'rectifier_serial_number',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10.60.30', ['1.30']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

