#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.70.80.130 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_sc200_generator_run_time_remaining
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_sc200_generator_run_time_remaining(item, _no_params, info):
    """
                check_sc200_generator_run_time_remaining function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    sc200_generator_run_time_remaining = None
    try:
        if info:
            if info[0][0]:
        	uptime = int(info[0][0])
                uptime = uptime / 100
                seconds = uptime % 60
                rem = uptime / 60
                minutes = rem % 60
                hours = (rem % 1440) / 60
                days = rem / 1440
                now = int(time.time())
                since = time.strftime("%c", time.localtime(now - uptime))
                state = 0
		infotext = "sc200_generator_run_time_remaining=%s=%dDays@%02dHours@%02dMinutes@%02dSeconds" % (since, days, hours, minutes, seconds)
    except Exception,e:
        infotext = "unknown_value"
    return (state, infotext, [("sc200_generator_run_time_remaining","%dDays@%02dHours@%02dMinutes@%02dSeconds" % (days, hours, minutes, seconds))])

# This check works on all SNMP hosts

check_info["sc200_generator_run_time_remaining"] = {
    'check_function':          check_sc200_generator_run_time_remaining,
    'service_description':     'sc200_generator_run_time_remaining',
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10.70',['80.130']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}

