#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.60.29 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_rectifier_current
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_sc200_highest_rectifier_heatsink_temp(item, _no_params, info):
    """
                check_sc200_highest_rectifier_heatsink_temp calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    sc200_highest_rectifier_heatsink_temp = None
    try:
        if info:
            if info[0][0]:
        	try:
                    sc200_highest_rectifier_heatsink_temp = float(info[0][0])
        	except Exception,e:
        	    sc200_highest_rectifier_heatsink_temp = info[0][0].replace(' ','@')
                state = 0
                infotext = "sc200_highest_rectifier_heatsink_temp=%s" % sc200_highest_rectifier_heatsink_temp
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("sc200_highest_rectifier_heatsink_temp",sc200_highest_rectifier_heatsink_temp)])

# This check works on all SNMP hosts

check_info["sc200_highest_rectifier_heatsink_temp"] = {
    'check_function':          check_sc200_highest_rectifier_heatsink_temp,
    'service_description':     'sc200_highest_rectifier_heatsink_temp',
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10',['60.29']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.1918.2.13.10.50.30").lower(),
    'has_perfdata': True,
}


