#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.60.30.1.170 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_sc200_lvd_state
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_sc200_lvd_state(item, _no_params, info):
    """
                check_sc200_lvd_state

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    lvd_state = None
    index =0
    perfdata = []
    try:
        for line in info:
            index= index + 1
            lvd_state = line[0]
            try:
                lvd_state = float(lvd_state)
            except Exception,e:
                lvd_state = line[0].replace(' ','@')
            state = 0
            perfdata.append(("sc200__%d_lvd_state" % index,lvd_state))
            infotext = "sc200_lvd_state=%s" % lvd_state
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,perfdata)

check_info["sc200_lvd_state"] = {
    'check_function':          check_sc200_lvd_state,
    'service_description':     'sc200_lvd_state',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10.70.75.50',['1.10']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

