#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.70.80.140 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_sc200_generator_state
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_sc200_generator_state(item, _no_params, info):
    """
                check_sc200_generator_state function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    sc200_generator_state = None
    try:
        if info:
            if info[0][0]:
        	try:
                    sc200_generator_state = float(info[0][0])
        	except Exception,e:
        	    sc200_generator_state = info[0][0].replace(' ','@')
                state = 0
		if int(sc200_generator_state) == int(85):
		    sc200_generator_state = "notRunning"
		if int(sc200_generator_state) == int(86):
                    sc200_generator_state = "running"
		if int(sc200_generator_state) == int(87):
                    sc200_generator_state = "unavailable"
		if int(sc200_generator_state) == int(88):
                    sc200_generator_state = "missing"
		else:
		    sc200_generator_state = None

                infotext = "sc200_generator_state=%s" % sc200_generator_state
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("sc200_generator_state",sc200_generator_state)])

# This check works on all SNMP hosts

check_info["sc200_generator_state"] = {
    'check_function':          check_sc200_generator_state,
    'service_description':     'sc200_generator_state',
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10.70',['80.140']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}

