#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.1918.2.13.10.90.15.60 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_sc200_phase_fail
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################

def check_sc200_phase_fail(item, _no_params, info):
    """
                check_sc200_phase_fail function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    sc200_phase_fail = None
    try:
        if info:
            if info[0][0]:
        	try:
                    phase_fail = float(info[0][0])
                    if int(phase_fail) == 0:
                        sc200_phase_fail = "0:-Ok"
                    elif int(phase_fail) == 1:
                        sc200_phase_fail= '2:-Failed'
                    elif int(phase_fail) == 2:
                        sc200_phase_fail= '2:-Unavailable'
                    elif int(phase_fail) == 3:
                        sc200_phase_fail= '3:-Missing'
        	except Exception,e:
        	    sc200_phase_fail = info[0][0].replace(' ','@')
                state = 0
                infotext = "sc200_phase_fail=%s" % sc200_phase_fail
    except Exception,e:
        infotext = "sc200_phase_fail=unknown_value"
    return (state,infotext,[("sc200_phase_fail",sc200_phase_fail)])

# This check works on all SNMP hosts

check_info["sc200_phase_fail"] = {
    'check_function':          check_sc200_phase_fail,
    'service_description':     'sc200_phase_fail',
    'snmp_info':               ('.1.3.6.1.4.1.1918.2.13.10.90',['15.60']),
    'snmp_scan_function':      lambda oid: "sc200" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
    'has_perfdata': True,
}

