#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_exicom_model_no_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################
#def inventory_system_base_swversion_invent(info):
#    if info[0][0]:
#        return [ (None, None) ]

def check_solar_total_rec_current(item, _no_params, info):
    """
                check_exicom_model_no_invent function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    total_rec_current=None
    try:
        if info:
            if info[0][0]:
                total_rec_current = info[0][0]
		try:
		    total_rec_current = float(total_rec_current)
		except Exception,e:
		    total_rec_current = info[0][0].replace(' ','@')
                state = 0
                infotext = "total_rec_current=%s" % total_rec_current
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("total_rec_current",total_rec_current)])


check_info["solar_total_rec_current"] = {
    'check_function':          check_solar_total_rec_current,
    'service_description':     'solar_total_rec_current',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.10', ['3.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

