#!/usr/bin/python
import binascii
"""
vlan Poller script.
This is part of device application. 
Poller script determines the vlan. 
poller script takes the snmp value of OID .1.3.6.1.4.1.161.19.3.2.1.55.0 from snmp agent of device at specific interval.
all ports status are sent to device application 
"""
# ######################################################################
# Function : check_exicom_model_no_invent
#
# Parameters: info (SNMP Output) _no_params(No Parameters)
#
# Output: service state and plugin output
# #####################################################################
#def inventory_system_base_swversion_invent(info):
#    if info[0][0]:
#        return [ (None, None) ]

def check_solar_hvlv_inventory_count(item, _no_params, info):
    """
                check_exicom_model_no_invent function calculates vlan

                Args:
                        item (str) Specific item on SNMP output on which we want to filter results
                
                Kwargs:
                        params (tuple) Check parameters for critical and warning state of service

                Returns:
                        state (int) :
                                        0 : OK
                                        1 : Warning
                                        2: Critical
                    3: unknown
                        infotext(string):
                                        plugin output
                                        Example : OK - vlan=1;;;;

                        Raises:
                               Exception
    """
    state = 3
    infotext = "unknown_value"
    hvlv_inventory_count=None
    try:
        if info:
            if info[0][0]:
                hvlv_inventory_count = info[0][0]
		try:
		    hvlv_inventory_count = float(hvlv_inventory_count)
		except Exception,e:
		    hvlv_inventory_count = info[0][0].replace(' ','@')
                state = 0
                infotext = "hvlv_inventory_count=%s" % hvlv_inventory_count
    except Exception,e:
        infotext = "unknown_value"
    return (state,infotext,[("hvlv_inventory_count",hvlv_inventory_count)])


check_info["solar_hvlv_inventory_count"] = {
    'check_function':          check_solar_hvlv_inventory_count,
    'service_description':     'solar_hvlv_inventory_count',
    'has_perfdata':         True,
    'snmp_info':               ('.1.3.6.1.4.1.38016.14.9.8', ['1.0']),
    'snmp_scan_function':      lambda oid: "m1000" in oid(".1.3.6.1.4.1.38016.14.1.1.0").lower(),
}

